-- ============================================================================
-- FanBar Arena - Comptes & engagement supporters (groupe G1A)
-- A executer une seule fois dans Supabase SQL Editor.
--
-- Cree les tables propres a notre groupe (prefixe g1a_) :
--   * g1a_profiles    : profil applicatif lie a auth.users (pseudo, role...)
--   * g1a_predictions : pronostics des supporters sur les evenements
--
-- Securite : Row Level Security activee partout. Un utilisateur ne peut ecrire
-- que ses propres lignes. Le role "gerant" ne peut PAS etre auto-attribue : il
-- s'obtient via la fonction SECURITY DEFINER g1a_claim_gerant(code).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1) Profils supporters / gerants
-- ----------------------------------------------------------------------------
create table if not exists public.g1a_profiles (
  id            uuid primary key references auth.users (id) on delete cascade,
  pseudo        text not null,
  role          text not null default 'client' check (role in ('client', 'gerant')),
  favorite_team text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists g1a_profiles_role_idx on public.g1a_profiles (role);

create or replace function public.set_g1a_profiles_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_g1a_profiles_updated_at on public.g1a_profiles;
create trigger set_g1a_profiles_updated_at
before update on public.g1a_profiles
for each row execute function public.set_g1a_profiles_updated_at();

alter table public.g1a_profiles enable row level security;

-- Lecture publique (classements / mur des supporters), pas de donnee sensible.
drop policy if exists "g1a_profiles read" on public.g1a_profiles;
create policy "g1a_profiles read"
on public.g1a_profiles for select
to anon, authenticated
using (true);

-- Chaque utilisateur cree uniquement SON profil.
drop policy if exists "g1a_profiles insert self" on public.g1a_profiles;
create policy "g1a_profiles insert self"
on public.g1a_profiles for insert
to authenticated
with check (auth.uid() = id);

-- Chaque utilisateur met a jour uniquement SON profil.
drop policy if exists "g1a_profiles update self" on public.g1a_profiles;
create policy "g1a_profiles update self"
on public.g1a_profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

-- Empeche l'escalade de privilege : le client ne peut pas modifier la colonne
-- "role" directement (seule la fonction SECURITY DEFINER le peut).
revoke update (role) on public.g1a_profiles from anon, authenticated;

-- ----------------------------------------------------------------------------
-- 2) Promotion au role "gerant" via code d'acces (anti auto-promotion)
--    Change le code ci-dessous puis garde-le secret.
-- ----------------------------------------------------------------------------
create or replace function public.g1a_claim_gerant(p_code text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_secret constant text := 'FANBAR-GERANT-2026';
begin
  if auth.uid() is null then
    raise exception 'Authentification requise';
  end if;
  if p_code is distinct from v_secret then
    return 'invalid';
  end if;
  update public.g1a_profiles set role = 'gerant' where id = auth.uid();
  return 'gerant';
end;
$$;

revoke all on function public.g1a_claim_gerant(text) from public;
grant execute on function public.g1a_claim_gerant(text) to authenticated;

-- ----------------------------------------------------------------------------
-- 3) Pronostics supporters sur les evenements FanBar
-- ----------------------------------------------------------------------------
create table if not exists public.g1a_predictions (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references auth.users (id) on delete cascade,
  event_id      bigint not null references public.g1a_events (id) on delete cascade,
  pseudo        text not null,
  predicted_home integer not null check (predicted_home >= 0 and predicted_home <= 30),
  predicted_away integer not null check (predicted_away >= 0 and predicted_away <= 30),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (user_id, event_id)
);

create index if not exists g1a_predictions_event_idx on public.g1a_predictions (event_id);

drop trigger if exists set_g1a_predictions_updated_at on public.g1a_predictions;
create trigger set_g1a_predictions_updated_at
before update on public.g1a_predictions
for each row execute function public.set_g1a_profiles_updated_at();

alter table public.g1a_predictions enable row level security;

drop policy if exists "g1a_predictions read" on public.g1a_predictions;
create policy "g1a_predictions read"
on public.g1a_predictions for select
to anon, authenticated
using (true);

drop policy if exists "g1a_predictions insert self" on public.g1a_predictions;
create policy "g1a_predictions insert self"
on public.g1a_predictions for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "g1a_predictions update self" on public.g1a_predictions;
create policy "g1a_predictions update self"
on public.g1a_predictions for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "g1a_predictions delete self" on public.g1a_predictions;
create policy "g1a_predictions delete self"
on public.g1a_predictions for delete
to authenticated
using (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- 4) Diffusions video (resumes / lives Coupe du Monde 2026 integres au site)
--    Lecture publique. Seuls les gerants peuvent ajouter/modifier/supprimer.
-- ----------------------------------------------------------------------------
create table if not exists public.g1a_broadcasts (
  id           bigint generated by default as identity primary key,
  title        text not null,
  youtube_id   text not null unique,
  match_label  text,
  kind         text not null default 'resume' check (kind in ('resume', 'live', 'best')),
  published_at timestamptz,
  created_by   uuid references auth.users (id) on delete set null,
  created_at   timestamptz not null default now()
);

alter table public.g1a_broadcasts enable row level security;

drop policy if exists "g1a_broadcasts read" on public.g1a_broadcasts;
create policy "g1a_broadcasts read"
on public.g1a_broadcasts for select
to anon, authenticated
using (true);

drop policy if exists "g1a_broadcasts write gerant" on public.g1a_broadcasts;
create policy "g1a_broadcasts write gerant"
on public.g1a_broadcasts for all
to authenticated
using (
  exists (
    select 1 from public.g1a_profiles p
    where p.id = auth.uid() and p.role = 'gerant'
  )
)
with check (
  exists (
    select 1 from public.g1a_profiles p
    where p.id = auth.uid() and p.role = 'gerant'
  )
);

-- Nettoyage d'anciens seeds (videos non disponibles / non integrables en France).
delete from public.g1a_broadcasts
where youtube_id in (
  'SlmYDbzHqjg', 'Wbal5ZuGeI8', 'MM5hUuEzH3g', 'gQOgcN7_IZE', '7DLR9gCjXHk', '7cFSYqlo-2w',
  'obVK3tuUXgs', 'eVPNdLv1ugQ', 'q3ppzcwriGE', 'F38RMQltGP0', '3Q8JGYb50MY', 'kjcC5ia95_Y'
);

-- Seed : resumes Coupe du Monde 2026 (chaines francaises).
insert into public.g1a_broadcasts (title, youtube_id, match_label, kind, published_at)
values
  ('France 3-1 Senegal - Resume et buts', 'gdaCaPqp0D4', 'France vs Senegal', 'resume', '2026-06-16T21:00:00Z'),
  ('France - Senegal - Resume et buts', 't2HIDkYd3cw', 'France vs Senegal', 'resume', '2026-06-16T20:30:00Z'),
  ('Pays-Bas - Japon - Resume', 'cupn9ARPukA', 'Pays-Bas vs Japon', 'resume', '2026-06-15T18:00:00Z'),
  ('Tous les buts des Bleus (eliminatoires)', 'LhPR2Gi-9xQ', 'Equipe de France', 'best', '2026-06-10T12:00:00Z'),
  ('France vs Senegal 3-1 - Resume', '8I2s_hs4TUU', 'France vs Senegal', 'resume', '2026-06-16T20:00:00Z'),
  ('France 3-1 Senegal - En direct du resume', 'CZ2CdOyXSho', 'France vs Senegal', 'resume', '2026-06-16T19:30:00Z')
on conflict (youtube_id) do nothing;
