-- Run this in Supabase SQL Editor.
-- It stores FanBar events: selected match, zone/team mapping, and card assignments.
-- The policies below let the site read and manage events with the publishable/anon key.

create table if not exists public.g1a_events (
  id bigint generated by default as identity primary key,
  name text not null,
  match_id text not null,
  competition text,
  home_team text not null,
  away_team text not null,
  kickoff_at timestamptz,
  zone_a_team text not null,
  zone_b_team text not null,
  zone_a_card text not null,
  zone_b_card text not null,
  status text not null default 'planned'
    check (status in ('planned', 'active', 'finished', 'archived')),
  final_home_score integer,
  final_away_score integer,
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.g1a_events
add column if not exists final_home_score integer;

alter table public.g1a_events
add column if not exists final_away_score integer;

alter table public.g1a_events
add column if not exists finished_at timestamptz;

create index if not exists g1a_events_match_id_idx
on public.g1a_events (match_id);

create index if not exists g1a_events_created_at_idx
on public.g1a_events (created_at desc);

create or replace function public.set_g1a_events_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_g1a_events_updated_at on public.g1a_events;
create trigger set_g1a_events_updated_at
before update on public.g1a_events
for each row
execute function public.set_g1a_events_updated_at();

alter table public.g1a_events enable row level security;

drop policy if exists "Allow public read fanbar events" on public.g1a_events;
create policy "Allow public read fanbar events"
on public.g1a_events
for select
to anon
using (true);

drop policy if exists "Allow public insert fanbar events" on public.g1a_events;
create policy "Allow public insert fanbar events"
on public.g1a_events
for insert
to anon
with check (true);

drop policy if exists "Allow public update fanbar events" on public.g1a_events;
create policy "Allow public update fanbar events"
on public.g1a_events
for update
to anon
using (true)
with check (true);

drop policy if exists "Allow public delete fanbar events" on public.g1a_events;
create policy "Allow public delete fanbar events"
on public.g1a_events
for delete
to anon
using (true);
