-- ============================================================================
-- FanBar Arena - Comptes & engagement supporters (groupe G1A)
-- A executer une seule fois dans Supabase SQL Editor.
--
-- Cree les tables propres a notre groupe (prefixe g1a_) :
--   * g1a_profiles    : profil applicatif lie a auth.users (pseudo, role...)
--   * g1a_predictions : pronostics des supporters sur les evenements
--
-- Securite : Row Level Security activee partout. Un utilisateur ne peut ecrire
-- que ses propres lignes. Le role "gerant" ne peut PAS etre auto-attribue : un
-- gerant existant promeut les autres via la fonction SECURITY DEFINER
-- g1a_set_role(). Le 1er gerant est designe par le bloc BOOTSTRAP (section 2.bis).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1) Profils supporters / gerants
-- ----------------------------------------------------------------------------
create table if not exists public.g1a_profiles (
  id            uuid primary key references auth.users (id) on delete cascade,
  pseudo        text not null,
  role          text not null default 'client' check (role in ('client', 'gerant')),
  favorite_team text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists g1a_profiles_role_idx on public.g1a_profiles (role);

create or replace function public.set_g1a_profiles_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_g1a_profiles_updated_at on public.g1a_profiles;
create trigger set_g1a_profiles_updated_at
before update on public.g1a_profiles
for each row execute function public.set_g1a_profiles_updated_at();

alter table public.g1a_profiles enable row level security;

-- Lecture publique (classements / mur des supporters), pas de donnee sensible.
drop policy if exists "g1a_profiles read" on public.g1a_profiles;
create policy "g1a_profiles read"
on public.g1a_profiles for select
to anon, authenticated
using (true);

-- Chaque utilisateur cree uniquement SON profil.
drop policy if exists "g1a_profiles insert self" on public.g1a_profiles;
create policy "g1a_profiles insert self"
on public.g1a_profiles for insert
to authenticated
with check (auth.uid() = id);

-- Chaque utilisateur met a jour uniquement SON profil.
drop policy if exists "g1a_profiles update self" on public.g1a_profiles;
create policy "g1a_profiles update self"
on public.g1a_profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

-- Empeche l'escalade de privilege : le client ne peut pas modifier la colonne
-- "role" directement (seule la fonction SECURITY DEFINER le peut).
revoke update (role) on public.g1a_profiles from anon, authenticated;

-- ----------------------------------------------------------------------------
-- 2) Gestion des roles : un GERANT peut promouvoir / retrograder d'autres comptes
--    (un simple client ne peut JAMAIS se promouvoir lui-meme).
-- ----------------------------------------------------------------------------
drop function if exists public.g1a_claim_gerant(text);

create or replace function public.g1a_set_role(p_target uuid, p_role text)
returns text
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Seul un gerant peut changer un role.
  if not exists (
    select 1 from public.g1a_profiles
    where id = auth.uid() and role = 'gerant'
  ) then
    raise exception 'Action reservee au gerant';
  end if;

  if p_role not in ('client', 'gerant') then
    raise exception 'Role invalide';
  end if;

  update public.g1a_profiles set role = p_role where id = p_target;
  return p_role;
end;
$$;

revoke all on function public.g1a_set_role(uuid, text) from public;
grant execute on function public.g1a_set_role(uuid, text) to authenticated;

-- ----------------------------------------------------------------------------
-- 2.bis) BOOTSTRAP : designer le compte gerant predefini.
--   1. Cree d'abord ce compte via la page /register du site.
--   2. Remplace l'email ci-dessous par celui de ce compte, puis execute :
-- ----------------------------------------------------------------------------
update public.g1a_profiles
set role = 'gerant'
where id = (select id from auth.users where email = 'marouane4142@gmail.com');

-- ----------------------------------------------------------------------------
-- 3) Pronostics supporters sur les evenements FanBar
-- ----------------------------------------------------------------------------
create table if not exists public.g1a_predictions (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references auth.users (id) on delete cascade,
  event_id      bigint not null references public.g1a_events (id) on delete cascade,
  pseudo        text not null,
  predicted_home integer not null check (predicted_home >= 0 and predicted_home <= 30),
  predicted_away integer not null check (predicted_away >= 0 and predicted_away <= 30),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (user_id, event_id)
);

create index if not exists g1a_predictions_event_idx on public.g1a_predictions (event_id);

drop trigger if exists set_g1a_predictions_updated_at on public.g1a_predictions;
create trigger set_g1a_predictions_updated_at
before update on public.g1a_predictions
for each row execute function public.set_g1a_profiles_updated_at();

alter table public.g1a_predictions enable row level security;

drop policy if exists "g1a_predictions read" on public.g1a_predictions;
create policy "g1a_predictions read"
on public.g1a_predictions for select
to anon, authenticated
using (true);

drop policy if exists "g1a_predictions insert self" on public.g1a_predictions;
create policy "g1a_predictions insert self"
on public.g1a_predictions for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "g1a_predictions update self" on public.g1a_predictions;
create policy "g1a_predictions update self"
on public.g1a_predictions for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "g1a_predictions delete self" on public.g1a_predictions;
create policy "g1a_predictions delete self"
on public.g1a_predictions for delete
to authenticated
using (auth.uid() = user_id);

-- ----------------------------------------------------------------------------
-- 4) Diffusions video (resumes / lives Coupe du Monde 2026 integres au site)
--    Lecture publique. Seuls les gerants peuvent ajouter/modifier/supprimer.
-- ----------------------------------------------------------------------------
create table if not exists public.g1a_broadcasts (
  id           bigint generated by default as identity primary key,
  title        text not null,
  youtube_id   text not null unique,
  match_label  text,
  kind         text not null default 'resume' check (kind in ('resume', 'live', 'best')),
  published_at timestamptz,
  created_by   uuid references auth.users (id) on delete set null,
  created_at   timestamptz not null default now()
);

alter table public.g1a_broadcasts enable row level security;

drop policy if exists "g1a_broadcasts read" on public.g1a_broadcasts;
create policy "g1a_broadcasts read"
on public.g1a_broadcasts for select
to anon, authenticated
using (true);

drop policy if exists "g1a_broadcasts write gerant" on public.g1a_broadcasts;
create policy "g1a_broadcasts write gerant"
on public.g1a_broadcasts for all
to authenticated
using (
  exists (
    select 1 from public.g1a_profiles p
    where p.id = auth.uid() and p.role = 'gerant'
  )
)
with check (
  exists (
    select 1 from public.g1a_profiles p
    where p.id = auth.uid() and p.role = 'gerant'
  )
);

-- Nettoyage d'anciens seeds (vidéos non disponibles, non intégrables ou non officielles).
delete from public.g1a_broadcasts
where youtube_id in (
  'SlmYDbzHqjg', 'Wbal5ZuGeI8', 'MM5hUuEzH3g', 'gQOgcN7_IZE', '7DLR9gCjXHk', '7cFSYqlo-2w',
  'obVK3tuUXgs', 'eVPNdLv1ugQ', 'q3ppzcwriGE', 'F38RMQltGP0', '3Q8JGYb50MY', 'kjcC5ia95_Y',
  'rVfGFqQ3WjE', '8pCqYi7FGBQ', 'Q9wdT5Y4E-c', 'x_nDqWbL0gI', 'J9bFMSEvt1c', 'UmHwkXCCrFY',
  'gdaCaPqp0D4', 't2HIDkYd3cw', 'cupn9ARPukA', '8I2s_hs4TUU', 'CZ2CdOyXSho',
  'qx7idI5vIgk', 'FFsVEBS-4B0', 'Ehjl6X3gHxo', 'eGsj5v9qq1Q', 'f1YgFG4DKk4', 'BxTp78Jvlaw'
);

-- Seed : highlights officiels FIFA de matchs Coupe du Monde 2026.
insert into public.g1a_broadcasts (title, youtube_id, match_label, kind, published_at)
values
  ('Highlights | France 3-1 Senegal | FIFA World Cup 2026', 'n3JDGlOwMJ4', 'France vs Senegal', 'resume', '2026-06-16T21:00:00Z'),
  ('Highlights | Belgium 1-1 Egypt | FIFA World Cup 2026', 'i8sD2Aea9_M', 'Belgium vs Egypt', 'resume', '2026-06-15T21:00:00Z'),
  ('Highlights | Austria 3-1 Jordan | FIFA World Cup 2026', 'pU-mPZcuENY', 'Austria vs Jordan', 'resume', '2026-06-17T21:00:00Z'),
  ('Highlights | Qatar 1-1 Switzerland | FIFA World Cup 2026', 'KVz43-eddIQ', 'Qatar vs Switzerland', 'resume', '2026-06-13T21:00:00Z'),
  ('Highlights | Spain 0-0 Cabo Verde | FIFA World Cup 2026', 'W9Z4ER9oX0k', 'Spain vs Cabo Verde', 'resume', '2026-06-13T20:00:00Z'),
  ('Highlights | Saudi Arabia 1-1 Uruguay | FIFA World Cup 2026', 'XrDExPcLCXY', 'Saudi Arabia vs Uruguay', 'resume', '2026-06-14T21:00:00Z')
on conflict (youtube_id) do update
  set title = excluded.title,
      match_label = excluded.match_label,
      kind = excluded.kind,
      published_at = excluded.published_at;

-- ----------------------------------------------------------------------------
-- 5) Alias des sujets ethylotest : un gerant peut renommer "Personne 3" en
--    "Lucas Liger". Lecture publique, ecriture reservee aux gerants.
-- ----------------------------------------------------------------------------
create table if not exists public.g1a_subject_aliases (
  subject_id text primary key,
  alias      text not null,
  updated_at timestamptz not null default now()
);

alter table public.g1a_subject_aliases enable row level security;

drop policy if exists "g1a_aliases read" on public.g1a_subject_aliases;
create policy "g1a_aliases read"
on public.g1a_subject_aliases for select
to anon, authenticated
using (true);

drop policy if exists "g1a_aliases write gerant" on public.g1a_subject_aliases;
create policy "g1a_aliases write gerant"
on public.g1a_subject_aliases for all
to authenticated
using (
  exists (select 1 from public.g1a_profiles p where p.id = auth.uid() and p.role = 'gerant')
)
with check (
  exists (select 1 from public.g1a_profiles p where p.id = auth.uid() and p.role = 'gerant')
);

-- ----------------------------------------------------------------------------
-- 5.bis) Liaison compte <-> sujet ethylotest : un gerant associe une personne
--    testee a un compte, qui pourra alors consulter SES stats d'alcoolemie.
-- ----------------------------------------------------------------------------
create table if not exists public.g1a_subject_links (
  subject_id text primary key,
  user_id    uuid not null references auth.users (id) on delete cascade,
  updated_at timestamptz not null default now()
);

create index if not exists g1a_subject_links_user_idx on public.g1a_subject_links (user_id);

alter table public.g1a_subject_links enable row level security;

drop policy if exists "g1a_links read" on public.g1a_subject_links;
create policy "g1a_links read"
on public.g1a_subject_links for select
to anon, authenticated
using (true);

drop policy if exists "g1a_links write gerant" on public.g1a_subject_links;
create policy "g1a_links write gerant"
on public.g1a_subject_links for all
to authenticated
using (
  exists (select 1 from public.g1a_profiles p where p.id = auth.uid() and p.role = 'gerant')
)
with check (
  exists (select 1 from public.g1a_profiles p where p.id = auth.uid() and p.role = 'gerant')
);

-- ----------------------------------------------------------------------------
-- 6) Statistiques capturees par evenement (classements de l'historique).
--    Renseignees automatiquement a la cloture d'un evenement.
-- ----------------------------------------------------------------------------
alter table public.g1a_events add column if not exists stat_avg_sound numeric;
alter table public.g1a_events add column if not exists stat_zone_a_sound numeric;
alter table public.g1a_events add column if not exists stat_zone_b_sound numeric;
alter table public.g1a_events add column if not exists stat_avg_temperature numeric;
alter table public.g1a_events add column if not exists stat_avg_alcohol numeric;
alter table public.g1a_events add column if not exists stat_peak_affluence integer;
